import type { EditorPick } from "../../data/editorPicks";

export const EDITOR_PICKS: EditorPick[] = [
  // Bengaluru
  {
    id: "blr-nandi-hills",
    city: "bengaluru",
    name: "Nandi Hills sunrise run",
    distanceKm: 60,
    days: 1,
    bestSeason: "Sep – Feb",
    modes: ["motorcycle", "car"],
    blurb: "Classic early-morning dash from Bengaluru into the clouds at Nandi Hills.",
    highlights: ["Sunrise viewpoint", "Tipu’s Drop", "Bhoga Nandeeshwara Temple"],
    difficulty: "easy",
  },
  {
    id: "blr-mysuru",
    city: "bengaluru",
    name: "Mysuru heritage loop",
    distanceKm: 146,
    days: 2,
    bestSeason: "Oct – Feb",
    modes: ["motorcycle", "car"],
    blurb: "Expressway blast to Mysuru for palaces, Chamundi Hill and evening lights.",
    highlights: ["Mysore Palace", "Chamundi Hill", "Brindavan Gardens"],
    difficulty: "easy",
  },
  {
    id: "blr-sakleshpur",
    city: "bengaluru",
    name: "Sakleshpur coffee country",
    distanceKm: 221,
    days: 2,
    bestSeason: "Sep – Feb",
    modes: ["motorcycle", "car"],
    blurb: "Western Ghats run into estate country and misty hills near Sakleshpur.",
    highlights: ["Manjarabad Fort", "Coffee estates", "Viewpoints on NH75"],
    difficulty: "moderate",
  },
  {
    id: "blr-chikmagalur",
    city: "bengaluru",
    name: "Chikmagalur coffee & peaks",
    distanceKm: 245,
    days: 3,
    bestSeason: "Oct – Feb",
    modes: ["motorcycle", "car"],
    blurb: "Longer Ghats ride into Chikmagalur, with Mullayanagiri and coffee estates.",
    highlights: ["Mullayanagiri", "Coffee estate stay", "Hirekolale Lake"],
    difficulty: "moderate",
  },
  {
    id: "blr-coorg",
    city: "bengaluru",
    name: "Coorg valleys and rivers",
    distanceKm: 265,
    days: 3,
    bestSeason: "Oct – Feb",
    modes: ["motorcycle", "car"],
    blurb: "Sweepers through Mysuru and into Coorg’s river valleys and plantations.",
    highlights: ["Raja’s Seat", "Abbey Falls", "Dubare elephant camp"],
    difficulty: "moderate",
  },
  {
    id: "blr-wayanad",
    city: "bengaluru",
    name: "Wayanad hills run",
    distanceKm: 279,
    days: 3,
    bestSeason: "Oct – Feb",
    modes: ["motorcycle", "car"],
    blurb: "Cross the Karnataka–Kerala border into Wayanad’s forests and lakes.",
    highlights: ["Banasura Sagar Dam", "Pookode Lake", "Edakkal Caves"],
    difficulty: "moderate",
  },
  {
    id: "blr-pondicherry",
    city: "bengaluru",
    name: "Pondicherry coastal drive",
    distanceKm: 330,
    days: 3,
    bestSeason: "Dec – Feb",
    modes: ["motorcycle", "car"],
    blurb: "Fast highways to the coast for French Quarter cafés and sunrise beaches.",
    highlights: ["Promenade Beach", "White Town cafés", "Auroville"],
    difficulty: "easy",
  },
  {
    id: "blr-kudremukh",
    city: "bengaluru",
    name: "Kudremukh mountain escape",
    distanceKm: 328,
    days: 3,
    bestSeason: "Oct – Feb",
    modes: ["motorcycle", "car"],
    blurb: "Western Ghats marathon into Kudremukh’s shola grasslands and forest roads.",
    highlights: ["Kudremukh National Park", "Scenic ghat sections", "Trek base villages"],
    difficulty: "moderate",
  },
  {
    id: "blr-hampi",
    city: "bengaluru",
    name: "Hampi ruins ride",
    distanceKm: 338,
    days: 3,
    bestSeason: "Oct – Mar",
    modes: ["motorcycle", "car"],
    blurb: "Overnight run to the Vijayanagara ruins along highways and countryside.",
    highlights: ["Virupaksha Temple", "Vittala Temple & stone chariot", "Sunset viewpoints"],
    difficulty: "easy",
  },
];