import type { EditorPick } from "../../data/editorPicks";

export const EDITOR_PICKS: EditorPick[] = [
  // Hyderabad
  {
    id: "hyd-bhongir",
    city: "hyderabad",
    name: "Bhongir Fort day ride",
    distanceKm: 50,
    days: 1,
    bestSeason: "Oct – Feb",
    modes: ["motorcycle", "car"],
    blurb: "Quick hop out to Bhongir’s hilltop fort with a short hike and views.",
    highlights: ["Bhongir Fort climb", "Yadadri temple detour"],
    difficulty: "easy",
  },
  {
    id: "hyd-ananthagiri",
    city: "hyderabad",
    name: "Ananthagiri Hills forest loop",
    distanceKm: 78,
    days: 2,
    bestSeason: "Oct – Mar",
    modes: ["motorcycle", "car"],
    blurb: "Weekend forest escape with streams, trails and cool Ananthagiri air.",
    highlights: ["Anantha Padmanabha Swamy Temple", "Viewpoints", "Forest walks"],
    difficulty: "easy",
  },
  {
    id: "hyd-bidar",
    city: "hyderabad",
    name: "Bidar fort and heritage",
    distanceKm: 141,
    days: 2,
    bestSeason: "Oct – Feb",
    modes: ["motorcycle", "car"],
    blurb: "Cross into Karnataka for Bidar’s fort complex and old‑town streets.",
    highlights: ["Bidar Fort", "Bahmani tombs", "Gurdwara Nanak Jhira Sahib"],
    difficulty: "easy",
  },
  {
    id: "hyd-warangal",
    city: "hyderabad",
    name: "Warangal Kakatiya trail",
    distanceKm: 145,
    days: 2,
    bestSeason: "Oct – Feb",
    modes: ["motorcycle", "car"],
    blurb: "Historic circuit through Warangal’s fort, thousand‑pillar temples and lakes.",
    highlights: ["Warangal Fort", "Thousand Pillar Temple", "Bhadrakali Lake"],
    difficulty: "easy",
  },
  {
    id: "hyd-nagarjuna-sagar",
    city: "hyderabad",
    name: "Nagarjuna Sagar dam run",
    distanceKm: 165,
    days: 2,
    bestSeason: "Oct – Mar",
    modes: ["motorcycle", "car"],
    blurb: "Ride out to the massive dam, reservoir views and nearby waterfalls.",
    highlights: ["Nagarjuna Sagar Dam", "Boat ride to island", "Ethipothala Falls"],
    difficulty: "easy",
  },
  {
    id: "hyd-srisailam",
    city: "hyderabad",
    name: "Srisailam ghats and temple",
    distanceKm: 215,
    days: 2,
    bestSeason: "Oct – Mar",
    modes: ["motorcycle", "car"],
    blurb: "Ghat‑section ride to Srisailam’s riverside temple town and viewpoints.",
    highlights: ["Mallikarjuna Temple", "Srisailam Dam views", "Ghat hairpins"],
    difficulty: "moderate",
  },
  {
    id: "hyd-bogatha-ramappa",
    city: "hyderabad",
    name: "Bogatha Falls & Ramappa loop",
    distanceKm: 276, // anchor on Bogatha; Ramappa is slightly closer
    days: 3,
    bestSeason: "Oct – Feb",
    modes: ["motorcycle", "car"],
    blurb: "Longer circuit combining Bogatha’s forest waterfall and Ramappa’s UNESCO‑listed temple.",
    highlights: ["Bogatha Waterfalls", "Ramappa Temple", "Rural Telangana backroads"],
    difficulty: "moderate",
  },
  {
    id: "hyd-hampi",
    city: "hyderabad",
    name: "Hampi ruins marathon",
    distanceKm: 381,
    days: 3,
    bestSeason: "Oct – Mar",
    modes: ["motorcycle", "car"],
    blurb: "Big‑mile highway run to Hampi’s boulder fields and temple ruins.",
    highlights: ["Virupaksha Temple", "Coracle rides on Tungabhadra", "Sunset viewpoints"],
    difficulty: "moderate",
  },
  {
    id: "hyd-maredumilli",
    city: "hyderabad",
    name: "Maredumilli rainforest ride",
    distanceKm: 428,
    days: 3,
    bestSeason: "Oct – Feb",
    modes: ["motorcycle", "car"],
    blurb: "Forest highways into Maredumilli’s streams, bamboo groves and eco‑stays.",
    highlights: ["Forest drives", "Local waterfalls", "Eco‑tourism stays"],
    difficulty: "moderate",
  },
];